### ISSUE TITLE
Feature Request: Render UI to RenderTexture attached to Camera

### ISSUE THREAD

**Issue by Onat-H** [alelievr/HDRP-UI-Camera-Stacking#1]
It would be great to be able to use the performance benefits of single-pass rendering when using a render texture output on the camera as well.

**Comment by alelievr** [comment]
Thanks for the suggestion! I added it to the backlog :)

**Comment by alelievr** [comment]
This feature has been added in aedadf494bac7f8607cb40f45f0f4d4a89b8ef59. It willl be available in the next release along with post process support (if I can make it work 😅)
