### ISSUE TITLE
Rendering to only one specified camera

### ISSUE THREAD

**Issue by gentlemanSoup** [alelievr/HDRP-UI-Camera-Stacking#10]
I want my UI Camera to only render to my my main camera. Currently, it renders to all my cameras, with no simple solution to disable this!

**Comment by alelievr** [comment]
Hello, I added a new field field this in the 1.2 version. You should be able to filter on which camera the UI is rendered using this option.
![image](https://user-images.githubusercontent.com/6877923/144858714-cc667f92-52ce-4fee-b128-f284789d35ae.png)
