### ISSUE TITLE
RenderTexture' does not contain a definition for 'depthStencilFormat' 

### ISSUE THREAD

**Issue by shiyamon** [alelievr/HDRP-UI-Camera-Stacking#11]
It seems RenderTexture.depthStencilFormat is not found in Unity2020.3.
Simply commenting-out line 132 in HDCameraUI.cs looks working.

**Comment by alelievr** [comment]
Hello, thanks for the report, the issue has been fixed in the 1.2.1 version.
Fix hash: f4331e37a50282af94b9825362f88d993bd24f2a
