### ISSUE TITLE
[Question] What is the benefit of using this technique compared to a Custom Pass?

### ISSUE THREAD

**Issue by StepanMynarik** [alelievr/HDRP-UI-Camera-Stacking#13]
Hi,

What is the benefit of using this technique compared to a Custom Pass when I just need to stack screen space UI that skips any post-processing over my main camera?

My Custom Pass config looks like this:
![image](https://user-images.githubusercontent.com/46678816/149517899-056d6055-4aa2-48a3-99d3-c9c9927b6399.png)

It works and performs well, but I'm always trying to understand every available solution out there :)

Is this repository's solution even faster? Or does it produce better visual quality? Or is it intended for some more complex UI scenarios?

Regards,
Stepan

**Comment by alelievr** [comment]
Hello,

The solution in this repository is supposed to be easier to use because it's closer to the original camera stacking workflow, in terms of performance it's the same as a UI custom pass.
