### ISSUE TITLE
Each UI have two drawcall?

### ISSUE THREAD

**Issue by WandingPace** [alelievr/HDRP-UI-Camera-Stacking#15]
![IR5HR}O`EQW_ 0$8(8P9IFO](https://user-images.githubusercontent.com/7385793/158378845-a38962ff-0d27-4655-8899-badd7320cef6.png)

I only create one image, but there are two drawcall

**Comment by STL1024** [comment]
Can this problem be solved?

**Comment by alelievr** [comment]
Fixed in this commit: https://github.com/alelievr/HDRP-UI-Camera-Stacking/commit/171a088d000dd136f8786779fd3c3e62925f5795 it will be included in the 1.4.0
