### ISSUE TITLE
Dependency error with Unity 2020.3.14f1

### ISSUE THREAD

**Issue by Peaj** [alelievr/HDRP-UI-Camera-Stacking#2]
The package caused a dependency issue with Unity 2020.3.14f1 because it requires a minimum HDRP version of 11.0.0.
The  maximum HDRP package version that can be installed in this Unity version is 10.5.1.
This leads to a dependency error and in my case it uninstalled the HDRP package completely.

**Comment by alelievr** [comment]
Ah yes indeed, I'll update the package json file as soon as I can

**Comment by alelievr** [comment]
Sorry I've just seen your PR, if you put the min version to `10.1.0` (first non-preview 10.x version of HDRP) I can merge your PR

**Comment by Peaj** [comment]
Sry I misread your version compatibility table. I missed the X's.
I changed the version requirement to 10.1.0.

**Comment by alelievr** [comment]
Thanks for the PR!
