### ISSUE TITLE
Unity 6 namespace error

### ISSUE THREAD

**Issue by sasa42** [alelievr/HDRP-UI-Camera-Stacking#26]
Hello,

Unity 6 (6000.0.7f1) shows this error.

![HDRPCamStackingUnity6](https://github.com/user-attachments/assets/671d6160-a716-4f4f-89a1-3cdd5e565009)

Could you support this preview version?

**Comment by alelievr** [comment]
Hey, thanks for the report. I pushed a new package version with a fix (1.4.3)
