### ISSUE TITLE
Feature request - Render To Texture

### ISSUE THREAD

**Issue by joshkbaker** [alelievr/HDRP-UI-Camera-Stacking#5]
Hi, I've been using a separate camera to render my minimap. 
It's basically a camera above the player that renders icons on each object with a minimap script on them.

Normal camera works fine using this technique (render to texture) but I imagine I'm using more power than I should for this basic effect. 

When I use this camera to do the same effect, it doesn't seem to render to texture and puts right across the screen.
With the other camera technique, it renders fine in the bottom left of the screen.

Thanks

![image](https://user-images.githubusercontent.com/11979160/132831466-427dd7b0-26bb-458d-97a7-e5cc5aab7373.png)

**Comment by alelievr** [comment]
Hello, which version are you using? The one on open UPM or master on github? The OpenUPM one doesn't support yet rendering to a texture

**Comment by joshkbaker** [comment]
I thought I was using the Master on github, does the master one include render to texture?

**Comment by alelievr** [comment]
> does the master one include render to texture?

Yes, when you put a render texture in the camera, the UI will be rendered to this render texture with master

**Comment by alelievr** [comment]
RenderTexture was officially shipped with the 1.1.0 release: https://github.com/alelievr/HDRP-UI-Camera-Stacking/releases/tag/1.1.0
