### ISSUE TITLE
RenderTexture not working

### ISSUE THREAD

**Issue by spxyz** [alelievr/HDRP-UI-Camera-Stacking#6]
I'm... trying, but it's not working. )

![2021-10-20_16-11-20](https://user-images.githubusercontent.com/11527631/138099403-3ee7bc47-7d3d-4f3d-96c2-25dd23f49ee7.png)

**Comment by alelievr** [comment]
Hello, This workflow have been fixed with the latest release: https://github.com/alelievr/HDRP-UI-Camera-Stacking/releases/tag/1.1.0

You need to enable the "Render In Camera Buffer" option in the HDCameraUI component to make it work
