### ISSUE TITLE
VR Support?

### ISSUE THREAD

**Issue by hybridherbst** [alelievr/HDRP-UI-Camera-Stacking#7]
It's great to see this referenced from the [official Unity blog](https://blog.unity.com/technology/get-acquainted-with-hdrp-settings-for-enhanced-performance)!

While I understand this is absolutely no guarantee for support here would still be great if this would indeed support VR where performance is pretty critical (and goes bad with a separate UI camera right now).

As far as I can see that would mostly mean supporting the right RT layout, and supporting stereo instancing in the compositing shader...

**Comment by alelievr** [comment]
Hello :) 

I looked into this and sadly adding VR support is more complicated than that, it requires another compositing system because it overlaps with the XRMirrorView in HDRP. I still want to add VR support but the API for that is not there yet.

Also, this package was mainly developed for screen-space UI which doesn't work for VR (the UI needs to be projected in world space to match the views).

**Comment by tkslan** [comment]
@alelievr any updates can be made to support VR ?

**Comment by alelievr** [comment]
Hey, I didn't had time to work on this unfortunately but I'm trying to officially integrate this work in the HDRP package with a new "UI" mode for the camera. 
The goal for this official implementation would be to also support XR. 

Btw, can you confirm that you need this package for "Screen-Space" UI in VR and not world space UI?
(i.e. a HUD like in this video with the score and HP: https://youtu.be/jVAI1LzKuUs?si=h60nRccyJxy8L-2e&t=318)

**Comment by DriesVRBase** [comment]
Just gonna leave a comment to say thanks for the package! For my project World space UI would be very useful but I understand that that isn't easy :)

**Comment by alelievr** [comment]
The issue with world space UI is that you need depth test in the shader and if the depth buffer is jittered (TAA, DLSS, etc.), then you can't use it outside of the Forward HDRP pass.
In this situation, you have to deal with the jittering of your objects when they are depth-tested either by trying to stabilize the depth (expensive and complicated) or try to fade out the problematic areas.

**Comment by DriesDeRidder** [comment]
Thanks for the explanation! I made it work now with 2 global custom pass volumes. Seems to work fine for now :)

**Comment by alelievr** [comment]
[like]  Antoine LELIEVRE reacted to your message:
________________________________

**Comment by alelievr** [comment]
I added VR support in the latest version as experimental so I'm going to close this issue.
There will probably be some things that don't work as expected inside the headset, so you can re-open new issues if that happens :)
