### ISSUE TITLE
UI Mask not working.

### ISSUE THREAD

**Issue by MPrzekop** [alelievr/HDRP-UI-Camera-Stacking#8]
UI Mask component seems to be ignored by the custom renderer. 
with standard camera
![image](https://user-images.githubusercontent.com/18519484/141874066-95382da0-d903-455c-bae3-21fe2f4f50bb.png)
with HD Camera UI
![image](https://user-images.githubusercontent.com/18519484/141874133-048f7580-684c-440f-9d0d-6026380b2d09.png)

Unity 2020.3.20f HDRP 10.7.0

**Comment by alelievr** [comment]
Hello, thanks for the bug report. This is due to the lack of depth buffer when rendering the UI elements, I'll make a fix

**Comment by alelievr** [comment]
That should be fixed with 1.1.1 release :) 
Fix hash: https://github.com/alelievr/HDRP-UI-Camera-Stacking/commit/bb85bbfb9d531b5a67a871d9b56ecacc00adfd1e
